* **Kod**:

  * :doc:`Błędy </contributing/code/bugs>` | 
  * :doc:`Patche </contributing/code/patches>` | 
  * :doc:`Bezpieczeństwo </contributing/code/security>` | 
  * :doc:`Testy </contributing/code/tests>` | 
  * :doc:`Standardy kodowania</contributing/code/standards>` | 
  * :doc:`Konwencja</contributing/code/conventions>` | 
  * :doc:`Licencja </contributing/code/license>`

* **Dokumentacja**:

  * :doc:`Przegląd </contributing/documentation/overview>` | 
  * :doc:`Format </contributing/documentation/format>` | 
  * :doc:`Tłumaczenia </contributing/documentation/translations>` | 
  * :doc:`Licencja </contributing/documentation/license>`

* **Społeczność**:

  * :doc:`Spotkania IRC </contributing/community/irc>` |
  * :doc:`Inne zasoby </contributing/community/other>`
